### ISSUE TITLE
I have problem 

### ISSUE THREAD

**Issue by Ranzware** [MrCryptoT/Crypto_Pricebot#5]
Hello .. thank you for the code .. i am a beginner trying to learn .. 

i have this problem after running the code 

File "/root/Crypto_Pricebot/pricebot.py", line 82
    response = session.get(url, params=parameters)
TabError: inconsistent use of tabs and spaces in indentation

what can i do to fix ?

**Comment by MrCryptoT** [comment]
Python is picky when it comes to mixing tabs with spaces, 
On Line 82 you quite likely have either a tab or a space, while using the other in all other places. 

(Check if you used tab instead of spaces to "indent" code ;) Sorry if my code had a wrong indent out of the box)

Happy coding and sorry for the long time to respond, I should enable push notifications again☕ 

Edit: While editing you introduced some syntax Error, I checked my code and it's fine. (see screenshot below).
To Fix it, feel free to use some syntax checker for python like https://extendsclass.com/python-tester.html for example =) 
![image](https://user-images.githubusercontent.com/8693733/152601845-227aa172-c590-4286-ab20-7ecd2c0f401f.png)
